- name: Uninstall the ingress nginx controller
  hosts: localhost
  connection: local

  tasks:
    - name: Uninstall ingress nginx
      ansible.builtin.include_role:
        name: "./helm/nginx"
      vars:
        ingress_nginx_uninstall: true
