persistence:
  type: pvc
  enabled: {{ persistence }}

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Mimir
        type: prometheus
        url: http://mimir-gateway.monitoring.svc.cluster.local/prometheus
        access: proxy
        isDefault: true
        jsonData:
          timeInterval: "60s"
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "infra"
          
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring.svc.cluster.local
        access: proxy
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "infra"
          
      - name: Tempo
        type: tempo
        url: http://tempo-query-frontend.monitoring.svc.cluster.local:3200
        access: proxy
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
        secureJsonData:
          httpHeaderValue1: "infra"

plugins:
  - grafana-lokiexplore-app
