spring:
  application:
    name: springapp
management:
  endpoints:
    web:
      exposure:
        # Expose health, standard metrics, and prometheus endpoints
        # include: health, metrics, prometheus
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://k8smonitoring-alloy-receiver.monitoring.svc.cluster.local:4318/v1/traces

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
      slo:
        http.server.requests: 50ms,100ms,200ms,500ms,1s,2s,5s
