- name: Add the Grafana repository to helm
  kubernetes.core.helm_repository:
    name: grafana-community
    repo_url: https://grafana-community.github.io/helm-charts

- name: Deploy Grafana with helm
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana-community/grafana
    chart_version: 12.7.1
    values: "{{ lookup('template', 'values.yml') | from_yaml }}"
    release_namespace: monitoring
    create_namespace: true
